config/routes.rb
Rails.application.routes.draw do
  resources :styles
  resources :beer_clubs
  resources :beer_clubs
  resources :memberships
  resources :users
  resources :beers
  resources :breweries
  resources :ratings, only: [:index, :new, :create, :destroy]
  resource :session, only: [:new, :create, :destroy]
  resources :places, only:[:index, :show]
  resources :breweries do
    post 'toggle_activity', on: :member
  end
  resources :users do
    post 'toggle_activity', on: :member
  end
  root 'breweries#index'
  get 'kaikki_bisset', to: 'beers#index'
  get 'ratings', to: 'ratings#index'
  get 'ratings/new', to:'ratings#new'
  post 'ratings', to: 'ratings#create'
  get 'signup', to: 'users#new'
  get 'signin', to: 'sessions#new'
  delete 'signout', to: 'sessions#destroy'
  get 'beerclubs', to:'beer_clubs#index'
  get 'beerclubs/new', to: 'beer_clubs#new'
  get 'places', to: 'places#index'
  get 'places/:id', to: 'places#show'
  post 'places', to: 'places#search'
  get 'styles', to: 'styles#index'
  get 'styles/:id', to: 'styles#show'
  get 'beerlist', to: 'beers#list'
  get 'brewerylist', to: 'breweries#list'
  get 'auth/:provider/callback', to: 'sessions#create_oauth'

end

app/models/beer.rb
class Beer < ActiveRecord::Base
  include RatingAverage

  belongs_to :brewery, touch: true
  has_many :ratings, dependent: :destroy
  has_many :raters, through: :ratings, source: :user
  belongs_to :style

  validates :name, length: {minimum: 1}
  validates :style_id, presence: true

  def average
    return 0 if ratings.empty?
    ratings.map{ |r| r.score }.sum / ratings.count.to_f
  end


  def pluralize_without_count(count, noun, text = nil)
    if count != 0
      count == 1 ? "an #{noun}#{text}" : "#{noun.pluralize}#{text}"
    end
  end

  def to_s
    "#{name} - #{brewery.name}"
  end
  def self.top(n)
    sorted_by_rating_in_desc_order = Beer.all.sort_by{ |b| -(b.average_rating||0)}
    return sorted_by_rating_in_desc_order.take(n)
  end
end

app/controllers/beers_controller.rb
class BeersController < ApplicationController
  before_action :set_beer, only: [:show, :edit, :update, :destroy]
  before_action :ensure_that_signed_in, except: [:index, :show, :list]
  before_action :ensure_that_admin, only: [:destroy]
  before_action :skip_if_cached, only:[:index]
  # GET /beers
  # GET /beers.json
  def index
    @beers = Beer.includes(:brewery, :style).all

    order = params[:order] || 'name'

    @beers = case order
               when 'name' then
                 @beers.sort_by { |b| b.name }
               when 'brewery' then
                 @beers.sort_by { |b| b.brewery.name }
               when 'style' then
                 @beers.sort_by { |b| b.style.name }
             end
  end

  # GET /beers/1
  # GET /beers/1.json
  def show
    @rating = Rating.new
    @rating.beer = @beer
    @style = @beer.style_id
  end

  # GET /beers/new
  def new
    @beer = Beer.new
    @breweries = Brewery.all
    @styles = Style.all
  end

  def list

  end

  # GET /beers/1/edit
  def edit
    @breweries = Brewery.all
    @styles = Style.all
  end

  # POST /beers
  # POST /beers.json
  def create
    ["beerlist-name", "beerlist-brewery", "beerlist-style"].each{ |f| expire_fragment(f) }
    @beer = Beer.new(beer_params)
    @styles = Style.all

    respond_to do |format|
      if @beer.save
        format.html { redirect_to beers_path, notice: 'Beer was successfully created.' }
        format.json { render :show, status: :created, location: @beer }
      else
        @breweries = Brewery.all
        format.html { render :new }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /beers/1
  # PATCH/PUT /beers/1.json
  def update
    ["beerlist-name", "beerlist-brewery", "beerlist-style"].each{ |f| expire_fragment(f) }
    respond_to do |format|
      if @beer.update(beer_params)
        format.html { redirect_to @beer, notice: 'Beer was successfully updated.' }
        format.json { render :show, status: :ok, location: @beer }
      else
        format.html { render :edit }
        format.json { render json: @beer.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /beers/1
  # DELETE /beers/1.json
  def destroy
    ["beerlist-name", "beerlist-brewery", "beerlist-style"].each{ |f| expire_fragment(f) }
    @beer.destroy
    respond_to do |format|
      format.html { redirect_to beers_url, notice: 'Beer was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_beer
    @beer = Beer.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def beer_params
    params.require(:beer).permit(:name, :style_id, :brewery_id)
  end

  def set_breweries_and_styles_for_template
    @breweries = Brewery.all
    @styles = ["Weizen", "Lager", "Pale ale", "IPA", "Porter"]
  end
  def skip_if_cached
    @order = params[:order] || 'name'
    return render :index if request.format.html? and fragment_exist?( 'beerlist' )
  end
end

app/helpers/beers_helper.rb
module BeersHelper
end

app/views/beers/_form.html.erb
<%= form_for(@beer) do |f| %>
  <% if @beer.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@beer.errors.count, "error") %> prohibited this beer from being saved:</h2>

      <ul>
      <% @beer.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :style %><br>
    <%= f.select :style_id, options_from_collection_for_select(@styles, :id, :name, selected: @beer.style_id) %>
  </div>
  <div class="field">
    <%= f.label :brewery %><br>
    <%= f.select :brewery_id, options_from_collection_for_select(@breweries, :id, :name, selected: @beer.brewery_id) %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/beers/_list.html.erb
<table class="table table-hover">
  <thead>
  <tr>
    <th> <%= link_to 'Name', beers_path(order:"name") %> </th>
    <th> <%= link_to 'Style', beers_path(order:"style") %> </th>
    <th> <%= link_to 'Brewery', beers_path(order:"brewery") %> </th>
  </tr>
  </thead>

  <tbody>
  <% beers.each do |beer| %>
      <tr>
        <td><%= link_to beer.name, beer %></td>
        <td><%= link_to beer.style.name, beer.style %></td>
        <td><%= link_to beer.brewery.name, beer.brewery %></td>
        <td><%= edit_and_destroy_buttons(beer) %></td>
      </tr>
  <% end %>
  </tbody>
</table>

app/views/beers/edit.html.erb
<h1>Editing Beer</h1>

<%= render 'form' %>

<%= link_to 'Show', @beer %> |
<%= link_to 'Back', beers_path %>

app/views/beers/index.html.erb
<h1>Beers</h1>
<% cache "beerlist-#{@order}", skip_digest: true do %>
    <p>Number of Beers in database: <%= @beers.count %></p>

    <%= render 'list', beers: @beers %>
<% end %>
<br>
<%= link_to 'List of all breweries', breweries_path, class: "btn btn-default" %>
<%= link_to 'New Beer', new_beer_path, class: "btn btn-primary" %>

app/views/beers/list.html.erb
<h2>Beers</h2>

<table id="beertable" class="table table-hover">
  <tr>
    <th> <a href="#" id="name">Name</a> </th>
    <th> <a href="#" id="style">Style</a> </th>
    <th> <a href="#" id="brewery">Brewery</a> </th>
  </tr>

</table>

app/views/beers/new.html.erb
<h1>Add new beer</h1>


<%= render 'form' %>

<p>Can't find your brewery or style? Add a new one:</p>
<%= link_to 'New Brewery', new_brewery_path, class:"btn btn-primary"  %> <%= link_to 'New Style', new_style_path, class: "btn btn-default" %>

app/views/beers/show.html.erb
<% cache @beer do %>

    <h2>
      <%= @beer.name %>
    </h2>

    <p>
      <strong><%= link_to @beer.style.name, @beer.style %></strong>
      brewed by
      <strong><%= link_to @beer.brewery.name, @beer.brewery %></strong>
    </p>

    <% if @beer.ratings.empty? %>
        <p>beer has not yet been rated! </p>
    <% else %>
        <p>Has <%= pluralize(@beer.ratings.count,'rating') %>, average <%= round(@beer.average_rating) %> </p>
    <% end %>

<% end %>

<% if current_user %>

    <h4>give a rating:</h4>

    <%= form_for(@rating) do |f| %>
        <%= f.hidden_field :beer_id %>
        score: <%= f.number_field :score %>
        <%= f.submit class:"btn btn-primary"  %>
    <% end %>

    <p></p>

<% end %>

<%= edit_and_destroy_buttons(@beer) %>